export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  INPUT_CHANGE: 'INPUT_CHANGE',
  UPDATE_NAME: 'UPDATE_NAME',
  CITY_INPUT_CHANGE: 'CITY_INPUT_CHANGE',
  UPDATE_CITY_NAME: 'UPDATE_CITY_NAME',
  CITY_FORECAST: 'CITY_FORECAST',
  GET_MOON_PHASE: 'GET_MOON_PHASE'
}
